"""add password col

Revision ID: 472349b02bf8
Revises: 3d99db53164f
Create Date: 2025-02-09 22:48:45.005636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '472349b02bf8'
down_revision: Union[str, None] = '3d99db53164f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.execute("UPDATE users SET password = 'default_password'")
    op.alter_column('users', 'password', nullable=False)
    op.alter_column('users', 'address',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    op.alter_column('users', 'address',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
